-- CATEGORIAS
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Lanche', true WHERE 'Lanche' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Bebida', true WHERE 'Bebida' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Acompanhamento', true WHERE 'Acompanhamento' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Sobremesa', true WHERE 'Sobremesa' NOT IN (SELECT NOME FROM CATEGORIA)

-- LANCHES
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Bacon', 'Pão, hambuguer, bacon, queijo', 29.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Bacon' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Salada', 'Pão, hambuguer, alface, tomate', 21.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Salada' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Egg', 'Pão, hambuguer, queijo, queijo', 23.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Egg' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Frango', 'Pão, frango, alface, queijo', 25.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Frango' NOT IN (SELECT NOME FROM PRODUTO)


-- BEBIDAS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Coca-Cola', '300ml', 6.9, (SELECT id FROM CATEGORIA WHERE nome = 'Bebida'), true, current_timestamp WHERE 'Coca-Cola' NOT IN (SELECT NOME FROM PRODUTO)

-- ACOMPANHAMENTOS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Batata simples', 'Batata frita de palito', 10.5, (SELECT id FROM CATEGORIA WHERE nome = 'Acompanhamento'), true, current_timestamp WHERE 'Batata simples' NOT IN (SELECT NOME FROM PRODUTO)

-- SOBREMESAS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Banana flambada', 'Deliciosa banada caramelizada com sorvete de creme', 18.5, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'Banana flambada' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Banana flambada', 'Deliciosa banada caramelizada com sorvete de creme', 18.5, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'X Bacon' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Banana flambada', 'Deliciosa banada caramelizada com sorvete de creme', 18.5, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'X Bacon' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Banana flambada', 'Deliciosa banada caramelizada com sorvete de creme', 18.5, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'X Bacon' NOT IN (SELECT NOME FROM PRODUTO)
