-- CATEGORIAS
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Lanche', true WHERE 'Lanche' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Bebida', true WHERE 'Bebida' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Acompanhamento', true WHERE 'Acompanhamento' NOT IN (SELECT NOME FROM CATEGORIA)
INSERT INTO CATEGORIA (NOME, STATUS_ATIVO) SELECT 'Sobremesa', true WHERE 'Sobremesa' NOT IN (SELECT NOME FROM CATEGORIA)

-- LANCHES
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Bacon', 'Pão, hambuguer, bacon, queijo', 29.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Bacon' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Salada', 'Pão, hambuguer, alface, tomate', 21.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Salada' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Egg', 'Pão, hambuguer, queijo, queijo', 23.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Egg' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'X Frango', 'Pão, frango, alface, queijo', 25.9, (SELECT id FROM CATEGORIA WHERE nome = 'Lanche'), true, current_timestamp WHERE 'X Frango' NOT IN (SELECT NOME FROM PRODUTO)

-- BEBIDAS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Coca cola', 'Refrigerante', 6.50, (SELECT id FROM CATEGORIA WHERE nome = 'Bebida'), true, current_timestamp WHERE 'Coca-Cola' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Fanta laranja', 'Refrigerante de laranja', 6.50, (SELECT id FROM CATEGORIA WHERE nome = 'Bebida'), true, current_timestamp WHERE 'Fanta laranja' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Guarana Antarctica', 'Refrigerante de guarana', 6.50, (SELECT id FROM CATEGORIA WHERE nome = 'Bebida'), true, current_timestamp WHERE 'Guarana Antarctica' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Del Valle uva', 'Suco de uva', 5.50, (SELECT id FROM CATEGORIA WHERE nome = 'Bebida'), true, current_timestamp WHERE 'Del Valle uva' NOT IN (SELECT NOME FROM PRODUTO)

-- ACOMPANHAMENTOS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Batata simples', 'Batata frita de palito', 10.5, (SELECT id FROM CATEGORIA WHERE nome = 'Acompanhamento'), true, current_timestamp WHERE 'Batata simples' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Batata prime', 'Batata frita com cheddar e bacon', 13.0, (SELECT id FROM CATEGORIA WHERE nome = 'Acompanhamento'), true, current_timestamp WHERE 'BBatata prime' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Nuggets', 'Nuggets de frango e molho barbecue', 12.5, (SELECT id FROM CATEGORIA WHERE nome = 'Acompanhamento'), true, current_timestamp WHERE 'Nuggets' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Salada mista', 'Mix de alface verde, alface roxo e tomate cereja', 10.5, (SELECT id FROM CATEGORIA WHERE nome = 'Acompanhamento'), true, current_timestamp WHERE 'Salada mista' NOT IN (SELECT NOME FROM PRODUTO)

-- SOBREMESAS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Açai da casa', 'Açaí com banana, leite ninho e mel', 21.0, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'Açai da casa' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Banana flambada', 'Deliciosa banada caramelizada com sorvete de creme', 18.5, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'Banana flambada' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Torta alemã', 'Maravilhosa torta com o toque especial da casa', 18.50, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'Torta alemãn' NOT IN (SELECT NOME FROM PRODUTO)
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, CATEGORIA_ID, STATUS_ATIVO, DATA_HORA_CRIACAO) SELECT 'Mousse de limão', 'A sobremesa mais queridinha depois da refeição', 18.50, (SELECT id FROM CATEGORIA WHERE nome = 'Sobremesa'), true, current_timestamp WHERE 'Mousse de limão' NOT IN (SELECT NOME FROM PRODUTO)

-- CLIENTES
INSERT INTO CLIENTE (CPF, EMAIL, FLAG_ATIVO, NOME, TELEFONE) SELECT '13737222070', 'thiago@gmail.com', true, 'Thiago Santos', '(11)99844-1233' WHERE '13737222070' NOT IN (SELECT CPF FROM CLIENTE)
INSERT INTO CLIENTE (CPF, EMAIL, FLAG_ATIVO, NOME, TELEFONE) SELECT '05040472056', 'fabiano@hotmail.com', true, 'Fabiano Siqueira', '(11)99324-0098' WHERE '05040472056' NOT IN (SELECT CPF FROM CLIENTE)
INSERT INTO CLIENTE (CPF, EMAIL, FLAG_ATIVO, NOME, TELEFONE) SELECT '28197205019', 'paularodrigues@gmail.com', true, 'Paula Rodrigues', '(11)94422-4223' WHERE '28197205019' NOT IN (SELECT CPF FROM CLIENTE)
INSERT INTO CLIENTE (CPF, EMAIL, FLAG_ATIVO, NOME, TELEFONE) SELECT '18900120093', 'fer_alves@gmail.com', true, 'Fernando Alves', '(11)88833-5290' WHERE '18900120093' NOT IN (SELECT CPF FROM CLIENTE)
INSERT INTO CLIENTE (CPF, EMAIL, FLAG_ATIVO, NOME, TELEFONE) SELECT '26426739014', 'ana_maciel@meuemail.com.br', true, 'Ana Laura Maciel', '(11)90242-6432' WHERE '26426739014' NOT IN (SELECT CPF FROM CLIENTE)

-- PEDIDO
INSERT INTO PEDIDO (DATA_HORA_CRIACAO, STATUS_PEDIDO, STATUS_PAGAMENTO, VALOR_TOTAL, CLIENTE_ID, OBSERVACAO) SELECT current_timestamp, 0, 0, 38.9, 1, 'Hambúrguer ao ponto' WHERE 1 NOT IN (SELECT CLIENTE_ID FROM PEDIDO)
INSERT INTO PEDIDO (DATA_HORA_CRIACAO, STATUS_PEDIDO, STATUS_PAGAMENTO, VALOR_TOTAL, CLIENTE_ID) SELECT current_timestamp, 0, 0, 43.5, 2 WHERE 2 NOT IN (SELECT CLIENTE_ID FROM PEDIDO)
INSERT INTO PEDIDO (DATA_HORA_CRIACAO, STATUS_PEDIDO, STATUS_PAGAMENTO, VALOR_TOTAL, CLIENTE_ID) SELECT current_timestamp, 0, 0, 29.00, 3 WHERE 3 NOT IN (SELECT CLIENTE_ID FROM PEDIDO)
INSERT INTO PEDIDO (DATA_HORA_CRIACAO, STATUS_PEDIDO, STATUS_PAGAMENTO, VALOR_TOTAL, CLIENTE_ID) SELECT current_timestamp, 0, 0, 48.40, 4 WHERE 4 NOT IN (SELECT CLIENTE_ID FROM PEDIDO)

-- PEDIDO PRODUTO

INSERT INTO PEDIDO_PRODUTO (PEDIDO_ID, PRODUTO_ID, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 1, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO_ID = 1 AND PRODUTO_ID = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO_ID, PRODUTO_ID, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 2, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO_ID = 2 AND PRODUTO_ID = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO_ID, PRODUTO_ID, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 3, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO_ID = 3 AND PRODUTO_ID = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO_ID, PRODUTO_ID, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 4, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO_ID = 4 AND PRODUTO_ID = 1)
/*
INSERT INTO PEDIDO_PRODUTO (PEDIDO, PRODUTO, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 1, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO = 1 AND PRODUTO = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO, PRODUTO, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 2, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO = 2 AND PRODUTO = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO, PRODUTO, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 3, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO = 3 AND PRODUTO = 1)
INSERT INTO PEDIDO_PRODUTO (PEDIDO, PRODUTO, PRECO_UNITARIO, QTDE_PRODUTO, SUB_TOTAL) SELECT 4, 1, 10, 1, 10 WHERE NOT EXISTS (SELECT 1 FROM PEDIDO_PRODUTO WHERE PEDIDO = 4 AND PRODUTO = 1)
*/